
IMAGE_REPOSITORY := irrealis/example-analysis
IMAGE_VERSION := $$(git describe --first-parent)
IMAGE_TAG := ${IMAGE_REPOSITORY}:${IMAGE_VERSION}

#docker-image:
#	@docker build -t 

testing:
	@echo IMAGE_TAG: ${IMAGE_TAG}
